# AMREX_HOME defines the directory in which we will find all the AMReX code.
# If you set AMREX_HOME as an environment variable, this line will be ignored
AMREX_HOME ?=/home/ThirdEye87/amrex
ETI_HOME ?= ../..

DEBUG     = FALSE
USE_MPI   = TRUE
USE_OMP   = FALSE

COMP      = gnu
DIM       = 3

USE_Z4C2 = TRUE
PROBLEM_LOADS_INITDATA = TRUE

include ../Make.ETI
