# AMREX_HOME defines the directory in which we will find all the AMReX code.
# If you set AMREX_HOME as an environment variable, this line will be ignored
AMREX_HOME ?=/home/ThirdEye87/amrex-master
ETI_HOME ?= ../..

DEBUG     = FALSE
USE_MPI   = FALSE
USE_OMP   = FALSE

COMP      = gnu
DIM       = 3

include ../Make.ETI
